const groups = [
  "Music Lovers",
  "Book Club",
  "Fitness Enthusiasts",
  "Nature Hikers",
  "Movie Buffs",
  "Tech Geeks",
  "Art Admirers",
  "Sports Fans",
  "Entrepreneurs",
  "Startup Enthusiasts",
  "Travel Addicts",
  "Foodies",
  "DIY Crafts",
  "Gamers",
  "Photographers",
  "Coding Enthusiasts",
  "Digital Marketers",
  "Writers & Poets",
  "Animal Lovers",
  "Environmentalists",
  "History Buffs",
  "Science Fiction Fans",
  "Gardening Club",
  "Language Learners",
  "Mental Health Support",
  "Charity Volunteers",
  "Designers",
  "Car Enthusiasts",
  "Fashionistas",
  "Meditation & Mindfulness",
  "Investors Club",
  "Yoga Practitioners",
  "Movie Makers",
  "Chess Players",
  "Data Science Enthusiasts",
  "Blockchain Experts",
  "Stock Market Analysts",
  "AI and Machine Learning",
  "Robotics Enthusiasts",
  "Astronomy Lovers",
  "Vintage Car Collectors",
  "Coffee Enthusiasts",
  "Meme Creators",
  "Podcasters",
  "Skateboarding Club",
  "Theater Performers",
  "Fitness Runners",
  "Cryptocurrency Traders",
  "Competitive Programmers",
  "Journalists & News",
];

module.exports = groups;
